from typing import Optional

from pydantic import BaseModel


class PropertyResponse(BaseModel):
    property_id: str
    address: str

    city: Optional[str] = None
    county: Optional[str] = None
    state: Optional[str] = None
    zip_code: Optional[str] = None

    property_type: Optional[str] = None

    apn: Optional[str] = None
    acres: Optional[float] = None
    square_feet: Optional[int] = None
    zoning: Optional[str] = None

    latitude: Optional[float] = None
    longitude: Optional[float] = None
    census_tract: Optional[str] = None
    block_group: Optional[str] = None
    flood_zone: Optional[str] = None
    flood_zone_subtype: Optional[str] = None
    special_flood_hazard_area: Optional[bool] = None
    flood_risk_level: Optional[str] = None
    flood_source: Optional[str] = None
    parcel_acres: Optional[float] = None
    jurisdiction: Optional[str] = None
    land_use: Optional[str] = None
    parcel_source: Optional[str] = None
    owner_name: Optional[str] = None
    owner_mailing_address: Optional[str] = None
    assessed_land_value: Optional[float] = None
    assessed_improvement_value: Optional[float] = None
    assessed_total_value: Optional[float] = None
    tax_year: Optional[int] = None
    tax_status: Optional[str] = None
    last_transfer_date: Optional[str] = None
    last_transfer_price: Optional[float] = None
    assessor_source: Optional[str] = None
    electric_provider: Optional[str] = None
    electric_service_evidence: Optional[str] = None
    gas_provider: Optional[str] = None
    gas_service_evidence: Optional[str] = None
    water_provider: Optional[str] = None
    water_service_evidence: Optional[str] = None
    sewer_provider: Optional[str] = None
    sewer_service_evidence: Optional[str] = None
    broadband_summary: Optional[str] = None
    broadband_evidence: Optional[str] = None
    utilities_source: Optional[str] = None
    research_quality_score: Optional[int] = None
    parcel_certainty: Optional[str] = None
    assessment_coverage: Optional[str] = None
    utility_confidence: Optional[str] = None
    research_risk_level: Optional[str] = None
    missing_research_items: Optional[list[str]] = None
    recommended_research_action: Optional[str] = None
    listing_url: Optional[str] = None
    listing_source: Optional[str] = None
    asking_price: Optional[float] = None
    unit_count: Optional[int] = None
    property_subtype: Optional[str] = None
    year_built: Optional[int] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[float] = None
    current_monthly_rent: Optional[float] = None
    current_monthly_rent_per_unit: Optional[float] = None
    current_annual_rent: Optional[float] = None
    occupancy_status: Optional[str] = None
    property_condition: Optional[str] = None
    rent_ready: Optional[bool] = None
    financial_data_source: Optional[str] = None
    estimated_market_value: Optional[float] = None
    after_repair_value: Optional[float] = None
    expected_operating_expense_percentage: Optional[float] = None
    estimated_monthly_rent: Optional[float] = None
    estimated_monthly_rent_per_unit: Optional[float] = None
    estimated_annual_rent: Optional[float] = None
    estimated_operating_expenses_monthly: Optional[float] = None
    estimated_operating_expenses_annual: Optional[float] = None
    estimated_noi_annual: Optional[float] = None
    estimated_cap_rate: Optional[float] = None
    estimated_monthly_cash_flow: Optional[float] = None
    gross_rent_multiplier: Optional[float] = None
    financial_analysis_confidence: Optional[str] = None
    rehab_needed: Optional[bool] = None
    rehab_scope_summary: Optional[str] = None
    rehab_items: Optional[list[str]] = None
    estimated_rehab_cost_low: Optional[float] = None
    estimated_rehab_cost_high: Optional[float] = None
    estimated_after_repair_value_low: Optional[float] = None
    estimated_after_repair_value_high: Optional[float] = None
    estimated_flip_profit_low: Optional[float] = None
    estimated_flip_profit_high: Optional[float] = None
    estimated_post_rehab_monthly_rent: Optional[float] = None
    estimated_post_rehab_annual_rent: Optional[float] = None
    financial_missing_items: Optional[list[str]] = None
    recommended_financial_action: Optional[str] = None
    listing_raw_text: Optional[str] = None
    listing_summary: Optional[str] = None
    listing_highlights: Optional[list[str]] = None
    listing_risks: Optional[list[str]] = None
    listing_missing_items: Optional[list[str]] = None
    listing_last_analyzed_at: Optional[str] = None
    listing_analysis_status: Optional[str] = None


class PropertyFinancialUpdate(BaseModel):
    listing_url: Optional[str] = None
    listing_source: Optional[str] = None
    asking_price: Optional[float] = None
    unit_count: Optional[int] = None
    property_subtype: Optional[str] = None
    year_built: Optional[int] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[float] = None
    current_monthly_rent: Optional[float] = None
    current_monthly_rent_per_unit: Optional[float] = None
    occupancy_status: Optional[str] = None
    property_condition: Optional[str] = None
    rent_ready: Optional[bool] = None
    financial_data_source: Optional[str] = None
    estimated_market_value: Optional[float] = None
    estimated_monthly_rent: Optional[float] = None
    estimated_monthly_rent_per_unit: Optional[float] = None
    expected_operating_expense_percentage: Optional[float] = None
    rehab_needed: Optional[bool] = None
    rehab_scope_summary: Optional[str] = None
    rehab_items: Optional[list[str]] = None
    estimated_rehab_cost_low: Optional[float] = None
    estimated_rehab_cost_high: Optional[float] = None
    after_repair_value: Optional[float] = None
    estimated_after_repair_value_low: Optional[float] = None
    estimated_after_repair_value_high: Optional[float] = None
    estimated_post_rehab_monthly_rent: Optional[float] = None
