import {api} from "../lib/api"; import type {Activity,Contact,ContactInput,CrmDashboard,Deadline,FollowUpTask,Note,SentOffer,WorkflowHistory,WorkflowState} from "../types/crm"; import type {WorkflowStage} from "../types/property";
const base=(id:string)=>`/properties/${id}`;
export const getContacts=(id:string)=>api.get<Contact[]>(`${base(id)}/contacts`); export const createContact=(id:string,v:Partial<ContactInput>)=>api.post<Contact>(`${base(id)}/contacts`,v); export const updateContact=(id:string,cid:string,v:Partial<ContactInput>)=>api.patch<Contact>(`${base(id)}/contacts/${cid}`,v); export const deleteContact=(id:string,cid:string)=>api.delete(`${base(id)}/contacts/${cid}`); export const makePrimary=(id:string,cid:string)=>api.post<Contact>(`${base(id)}/contacts/${cid}/primary`,{});
export const getTasks=(id:string)=>api.get<FollowUpTask[]>(`${base(id)}/tasks`); export const createTask=(id:string,v:Partial<FollowUpTask>)=>api.post<FollowUpTask>(`${base(id)}/tasks`,v); export const updateTask=(id:string,tid:string,v:Partial<FollowUpTask>)=>api.patch<FollowUpTask>(`${base(id)}/tasks/${tid}`,v); export const deleteTask=(id:string,tid:string)=>api.delete(`${base(id)}/tasks/${tid}`); export const setTaskComplete=(id:string,tid:string,complete:boolean)=>api.post<FollowUpTask>(`${base(id)}/tasks/${tid}/${complete?"complete":"reopen"}`,{});
export const getNotes=(id:string)=>api.get<Note[]>(`${base(id)}/notes`); export const createNote=(id:string,v:Partial<Note>)=>api.post<Note>(`${base(id)}/notes`,v); export const deleteNote=(id:string,nid:string)=>api.delete(`${base(id)}/notes/${nid}`); export const pinNote=(id:string,nid:string)=>api.post<Note>(`${base(id)}/notes/${nid}/pin`,{});
export const getWorkflow=(id:string)=>api.get<WorkflowState>(`${base(id)}/workflow`); export const changeStage=(id:string,to_stage:WorkflowStage,reason?:string)=>api.post<WorkflowState>(`${base(id)}/workflow/stage`,{to_stage,reason}); export const getWorkflowHistory=(id:string)=>api.get<WorkflowHistory[]>(`${base(id)}/workflow/history`); export const getActivity=(id:string)=>api.get<Activity[]>(`${base(id)}/activity`);
export const getDeadlines=(id:string)=>api.get<Deadline[]>(`${base(id)}/deadlines`); export const createDeadline=(id:string,v:Partial<Deadline>)=>api.post<Deadline>(`${base(id)}/deadlines`,v); export const deleteDeadline=(id:string,did:string)=>api.delete(`${base(id)}/deadlines/${did}`);
export const getSentOffers=(id:string)=>api.get<SentOffer[]>(`${base(id)}/sent-offers`); export const createSentOffer=(id:string,v:Partial<SentOffer>)=>api.post<SentOffer>(`${base(id)}/sent-offers`,v);
export const getCrmDashboard=()=>api.get<CrmDashboard>("/crm/dashboard");
