create table if not exists organizations(organization_id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists profiles(user_id uuid primary key references auth.users(id) on delete cascade,display_name text,email text,phone text,avatar_url text,default_organization_id uuid references organizations(organization_id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists organization_members(membership_id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(organization_id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text not null check(role in('owner','admin','acquisitions_manager','analyst','viewer')),status text not null check(status in('invited','active','suspended','removed')),invited_email text,invited_by uuid references auth.users(id),joined_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists uq_active_member_user on organization_members(organization_id,user_id) where user_id is not null and status in('invited','active');
create unique index if not exists uq_pending_member_email on organization_members(organization_id,lower(invited_email)) where invited_email is not null and status in('invited','active');
create table if not exists organization_invitations(invitation_id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(organization_id) on delete cascade,membership_id uuid not null references organization_members(membership_id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null,accepted_at timestamptz,created_at timestamptz not null default now());
create table if not exists organization_audit_events(audit_id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(organization_id) on delete cascade,actor_user_id uuid references auth.users(id),event_type text not null,entity_type text,entity_id text,metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());

insert into organizations(organization_id,name,slug) values('00000000-0000-0000-0000-000000000001','Property Intelligence Development','property-intelligence-development') on conflict(organization_id) do nothing;
do $$ declare t text; begin foreach t in array array['properties','property_media','property_media_analysis','property_condition_analysis','repair_cost_profiles','repair_cost_items','property_comparables','property_comparable_analysis','property_strategy_analysis','property_strategy_results','property_offer_analysis','property_financing_scenarios','property_financing_analysis','property_contacts','property_follow_up_tasks','property_notes','property_workflow_history','property_activity','property_deadlines','property_sent_offers','property_notifications','communication_templates','property_communications','share_intake'] loop if to_regclass(t) is not null then execute format('alter table %I add column if not exists organization_id uuid references organizations(organization_id)',t);execute format('update %I set organization_id=$1 where organization_id is null',t) using '00000000-0000-0000-0000-000000000001'::uuid;execute format('alter table %I alter column organization_id set not null',t);execute format('create index if not exists %I on %I(organization_id)', 'idx_'||t||'_organization',t);end if;end loop;end $$;
alter table communication_templates drop constraint if exists communication_templates_template_name_version_key;
create unique index if not exists uq_communication_template_org_name_version on communication_templates(organization_id,template_name,version);
create unique index if not exists uq_properties_org_apn on properties(organization_id,apn) where apn is not null;

create or replace function request_organization_id() returns uuid language sql stable as $$select nullif(current_setting('request.headers',true)::json->>'x-organization-id','')::uuid$$;
create or replace function active_org_role(org uuid) returns text language sql stable security definer set search_path=public as $$select role from organization_members where organization_id=org and user_id=auth.uid() and status='active' limit 1$$;
create or replace function active_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$select active_org_role(org) is not null$$;
create or replace function org_can_write(org uuid) returns boolean language sql stable security definer set search_path=public as $$select coalesce(active_org_role(org) in('owner','admin','acquisitions_manager'),false)$$;
create or replace function org_can_analyze(org uuid) returns boolean language sql stable security definer set search_path=public as $$select coalesce(active_org_role(org) in('owner','admin','acquisitions_manager','analyst'),false)$$;
create or replace function set_request_organization() returns trigger language plpgsql as $$begin if new.organization_id is null then new.organization_id:=request_organization_id();end if;return new;end$$;
create or replace function enforce_membership_safeguards() returns trigger language plpgsql security definer set search_path=public as $$
declare org uuid;caller_role text;
begin
 org:=case when tg_op='DELETE' then old.organization_id else new.organization_id end;
 if auth.role()='service_role' then if tg_op='DELETE' then return old;else return new;end if;end if;
 caller_role:=active_org_role(org);
 if tg_op='UPDATE' and new.user_id=auth.uid() and old.status='invited' and new.status='active' and new.role=old.role then return new;end if;
 if caller_role not in('owner','admin') then raise exception 'Member management permission required' using errcode='42501';end if;
 if tg_op<>'DELETE' and new.role='owner' and (tg_op='INSERT' or old.role<>'owner') and caller_role<>'owner' then raise exception 'Only an owner can promote another owner' using errcode='42501';end if;
 if tg_op in('UPDATE','DELETE') and old.role='owner' and old.status='active' and (tg_op='DELETE' or new.role<>'owner' or new.status<>'active') and (select count(*) from organization_members where organization_id=org and role='owner' and status='active')<=1 then raise exception 'The final active owner cannot be removed, suspended, or demoted' using errcode='23514';end if;
 if tg_op='DELETE' then return old;else return new;end if;
end$$;
drop trigger if exists enforce_membership_safeguards on organization_members;
create trigger enforce_membership_safeguards before insert or update or delete on organization_members for each row execute function enforce_membership_safeguards();

do $$ declare t text; begin foreach t in array array['properties','property_media','property_media_analysis','property_condition_analysis','repair_cost_profiles','repair_cost_items','property_comparables','property_comparable_analysis','property_strategy_analysis','property_strategy_results','property_offer_analysis','property_financing_scenarios','property_financing_analysis','property_contacts','property_follow_up_tasks','property_notes','property_workflow_history','property_activity','property_deadlines','property_sent_offers','property_notifications','communication_templates','property_communications','share_intake'] loop if to_regclass(t) is not null then execute format('alter table %I enable row level security',t);execute format('drop policy if exists org_read on %I',t);execute format('drop policy if exists org_write on %I',t);execute format('create policy org_read on %I for select using (organization_id=request_organization_id() and active_org_member(organization_id))',t);execute format('create policy org_write on %I for all using (organization_id=request_organization_id() and org_can_write(organization_id)) with check (organization_id=request_organization_id() and org_can_write(organization_id))',t);execute format('drop trigger if exists set_request_organization on %I',t);execute format('create trigger set_request_organization before insert on %I for each row execute function set_request_organization()',t);end if;end loop;end $$;
do $$ declare t text; begin foreach t in array array['property_media_analysis','property_condition_analysis','property_comparables','property_comparable_analysis','property_strategy_analysis','property_strategy_results','property_offer_analysis','property_financing_scenarios','property_financing_analysis','repair_cost_profiles','repair_cost_items'] loop if to_regclass(t) is not null then execute format('drop policy if exists analyst_write on %I',t);execute format('create policy analyst_write on %I for all using (organization_id=request_organization_id() and org_can_analyze(organization_id)) with check (organization_id=request_organization_id() and org_can_analyze(organization_id))',t);end if;end loop;end $$;
alter table organizations enable row level security;alter table organization_members enable row level security;alter table profiles enable row level security;alter table organization_invitations enable row level security;alter table organization_audit_events enable row level security;
drop policy if exists organization_member_read on organizations;drop policy if exists organization_admin_update on organizations;drop policy if exists member_read on organization_members;drop policy if exists member_owner_admin_write on organization_members;drop policy if exists own_profile on profiles;drop policy if exists invitation_admin on organization_invitations;drop policy if exists audit_read on organization_audit_events;
create policy organization_member_read on organizations for select using(active_org_member(organization_id));create policy organization_admin_update on organizations for update using(active_org_role(organization_id) in('owner','admin'));
create policy member_read on organization_members for select using(active_org_member(organization_id));create policy member_owner_admin_write on organization_members for all using(active_org_role(organization_id) in('owner','admin')) with check(active_org_role(organization_id) in('owner','admin'));
create policy own_profile on profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());create policy invitation_admin on organization_invitations for all using(active_org_role(organization_id) in('owner','admin')) with check(active_org_role(organization_id) in('owner','admin'));create policy audit_read on organization_audit_events for select using(active_org_role(organization_id) in('owner','admin'));
