import {useCallback,useEffect,useRef,useState} from "react";
import {getContacts} from "../../services/crmService";
import {createDraft,getCommunicationConfig,getMessages,getTemplates,previewTemplate,sendMessage,updateConsent} from "../../services/communicationService";
import type {Contact} from "../../types/crm";
import type {Channel,CommunicationConfig,CommunicationTemplate,Message} from "../../types/communication";
const approved=["seller_first_name","seller_last_name","property_address","offer_amount","offer_expiration","follow_up_date","user_name","company_name","callback_number","custom_notes"];type Feedback={kind:"success"|"error";text:string}|null;
export default function CommunicationsSection({propertyId,address}:{propertyId:string;address:string}){
 const [contacts,setContacts]=useState<Contact[]>([]),[templates,setTemplates]=useState<CommunicationTemplate[]>([]),[messages,setMessages]=useState<Message[]>([]),[config,setConfig]=useState<CommunicationConfig|null>(null);
 const [contactId,setContactId]=useState(""),[channel,setChannel]=useState<Channel>("email"),[templateId,setTemplateId]=useState(""),[variables,setVariables]=useState<Record<string,string>>({property_address:address}),[preview,setPreview]=useState<{subject?:string;body:string}|null>(null),[followUp,setFollowUp]=useState(false);
 const [loadingError,setLoadingError]=useState(""),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null);
 const savingRef=useRef(false);
 const load=useCallback(async()=>{try{const [c,t,m,cfg]=await Promise.all([getContacts(propertyId),getTemplates(),getMessages(propertyId),getCommunicationConfig()]);setContacts(c);setTemplates(t);setMessages(m);setConfig(cfg);setContactId(current=>current||c.find(x=>x.is_primary)?.contact_id||c[0]?.contact_id||"");setLoadingError("");}catch(e){setLoadingError(e instanceof Error?e.message:"Communications unavailable.")}},[propertyId]);useEffect(()=>{void load()},[load]);
 const contact=contacts.find(x=>x.contact_id===contactId),selected=templates.find(x=>x.template_id===templateId),consent=channel==="email"?contact?.email_consent_status:contact?.sms_consent_status,noSeller=contacts.length===0;useEffect(()=>{if(contact)setVariables(v=>({...v,seller_first_name:contact.first_name||"",seller_last_name:contact.last_name||""}))},[contact]);
 const edited=()=>setFeedback(null);const jumpToSeller=()=>{const target=document.getElementById("crm-contact");target?.scrollIntoView({behavior:"smooth",block:"center"});target?.focus()};
 const save=async()=>{if(savingRef.current||!contactId)return;savingRef.current=true;setSaving(true);setFeedback(null);try{const saved=await createDraft(propertyId,{contact_id:contactId,channel,template_id:templateId||undefined,subject:preview?.subject,body:preview?.body||"",variables,create_follow_up:followUp,follow_up_title:"Follow up on "+channel+" draft"});await load();setFeedback({kind:"success",text:"Draft saved. "+new Date(saved.created_at).toLocaleTimeString()});}catch(e){setFeedback({kind:"error",text:e instanceof Error?e.message:"Draft could not be saved."})}finally{savingRef.current=false;setSaving(false)}};
 return <section className="command-card"><p className="eyebrow">Seller communications</p><h2>Email and SMS drafts</h2><p className="underwriting-disclaimer">Drafting only by default. This feature does not provide legal compliance guarantees.</p>{loadingError&&<p className="media-error">{loadingError}</p>}
  {noSeller&&<div className="underwriting-disclaimer"><strong>Add a seller contact before creating a communication draft.</strong><p>Preview and draft controls are disabled because every message requires a seller and consent snapshot.</p><button onClick={jumpToSeller}>Go to seller contacts</button></div>}
  <div className="property-snapshot"><div><span>Primary seller</span><strong>{contact?[contact.first_name,contact.last_name].filter(Boolean).join(" ")||contact.company_name:"No seller contact"}</strong></div><div><span>Consent</span><strong>{consent||"unknown"}</strong></div></div>{contact?.do_not_contact&&<p className="media-error"><strong>DO NOT CONTACT</strong></p>}
  <div className="comparable-form"><label>Seller<select disabled={noSeller||saving} value={contactId} onChange={e=>{setContactId(e.target.value);edited()}}>{contacts.map(c=><option key={c.contact_id} value={c.contact_id}>{[c.first_name,c.last_name].filter(Boolean).join(" ")||c.company_name}</option>)}</select></label><label>Channel<select disabled={noSeller||saving} value={channel} onChange={e=>{setChannel(e.target.value as Channel);setTemplateId("");setPreview(null);edited()}}><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Template<select disabled={noSeller||saving} value={templateId} onChange={e=>{setTemplateId(e.target.value);setPreview(null);edited()}}><option value="">Custom draft</option>{templates.filter(t=>t.active&&t.channel===channel).map(t=><option key={t.template_id} value={t.template_id}>{t.template_name}</option>)}</select></label></div>
  <h3>Approved variables</h3><div className="comparable-form">{approved.map(key=><label key={key}>{key.replaceAll("_"," ")}<input disabled={noSeller||saving} value={variables[key]||""} onChange={e=>{setVariables({...variables,[key]:e.target.value});edited()}}/></label>)}</div>
  <button disabled={noSeller||saving||!selected} onClick={()=>void (async()=>{if(selected){setPreview(await previewTemplate(selected.template_id,variables));edited()}})()}>Render preview</button>{preview&&<div className="crm-section"><strong>{preview.subject||"SMS preview"}</strong><p style={{whiteSpace:"pre-wrap"}}>{preview.body}</p></div>}
  <label><input disabled={noSeller||saving} type="checkbox" checked={followUp} onChange={e=>{setFollowUp(e.target.checked);edited()}}/> Create a follow-up task explicitly</label>
  <div className="crm-quick-actions"><button disabled={noSeller||saving||!contactId||(!templateId&&!preview?.body)} onClick={()=>void save()}>{saving?"Saving…":"Save Draft"}</button><button disabled={!config?.send_available} title={config?.blocked_reason}>Send</button></div>
  {feedback&&<p role="status" className={feedback.kind==="error"?"media-error":"draft-success"}>{feedback.text}</p>}{!config?.send_available&&<p className="underwriting-disclaimer">{config?.blocked_reason||"External communications are unavailable."}</p>}
  {contact&&<div className="crm-section"><h3>Consent editor</h3><div className="crm-inline"><select value={contact.email_consent_status||"unknown"} onChange={e=>void updateConsent(propertyId,contact.contact_id,{email_consent_status:e.target.value}).then(load)}>{["unknown","consented","transactional_only","opted_out","prohibited"].map(x=><option key={x}>{x}</option>)}</select><select value={contact.sms_consent_status||"unknown"} onChange={e=>void updateConsent(propertyId,contact.contact_id,{sms_consent_status:e.target.value}).then(load)}>{["unknown","consented","transactional_only","opted_out","prohibited"].map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={contact.do_not_contact||false} onChange={e=>void updateConsent(propertyId,contact.contact_id,{do_not_contact:e.target.checked}).then(load)}/> Do not contact</label></div></div>}
  <div className="crm-section"><h3>Draft and message history</h3>{messages.map(m=><div className="crm-row" key={m.message_id}><span><strong>{m.channel.toUpperCase()} · {m.status}</strong><small>{m.subject||m.body.slice(0,80)} · {new Date(m.created_at).toLocaleString()}</small>{m.failure_reason&&<small className="media-error">{m.failure_reason}</small>}</span><span>{m.related_offer_id&&<small>Offer {m.related_offer_id}</small>}{m.related_task_id&&<small>Task {m.related_task_id}</small>}<button disabled={!config?.send_available||!(["draft","scheduled"].includes(m.status))} onClick={()=>void sendMessage(propertyId,m.message_id,true).then(load)}>Send</button></span></div>)}</div>
 </section>
}
