import { useCallback, useEffect, useMemo, useState } from "react";
import { analyzeComparables, createComparable, deleteComparable, getComparableAnalysis, listComparables, updateComparable } from "../../services/comparableService";
import type { ComparableAnalysis, ComparableInput, ComparableType, PropertyComparable } from "../../types/comparable";

const money = (value?: number) => value == null ? "—" : value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
type FormState = Record<string, string> & { comparable_type: ComparableType };
const emptyForm = (type: ComparableType): FormState => ({ comparable_type: type, source_name: "", source_url: "", source_record_id: "", address: "", distance_miles: "", property_type: "", property_subtype: "", unit_count: "", bedrooms: "", bathrooms: "", square_feet: "", lot_acres: "", year_built: "", condition: "", sale_price: "", sale_date: "", monthly_rent: "", listing_date: "", status: "", notes: "" });

export default function ComparablesSection({ propertyId }: { propertyId: string }) {
  const [tab, setTab] = useState<ComparableType>("sale"); const [items, setItems] = useState<PropertyComparable[]>([]);
  const [analysis, setAnalysis] = useState<ComparableAnalysis | null>(null); const [form, setForm] = useState<FormState>(emptyForm("sale"));
  const [editing, setEditing] = useState<string | null>(null); const [sort, setSort] = useState<"match_score" | "distance_miles" | "date" | "value">("match_score");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const refresh = useCallback(async () => { try { const values = await listComparables(propertyId); setItems(values); setAnalysis(await getComparableAnalysis(propertyId).catch(() => null)); setError(""); } catch (err) { setError(message(err)); } }, [propertyId]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (!editing) setForm(emptyForm(tab)); }, [tab, editing]);
  const shown = useMemo(() => items.filter((item) => item.comparable_type === tab).sort((a, b) => sort === "distance_miles" ? sortValue(a, sort) - sortValue(b, sort) : sortValue(b, sort) - sortValue(a, sort)), [items, tab, sort]);

  async function save() { setBusy(true); setError(""); try { const value = payload(form); if (editing) await updateComparable(propertyId, editing, value); else await createComparable(propertyId, value); setEditing(null); setForm(emptyForm(tab)); await refresh(); } catch (err) { setError(message(err)); } finally { setBusy(false); } }
  async function analyze() { setBusy(true); try { setAnalysis(await analyzeComparables(propertyId)); await refresh(); } catch (err) { setError(message(err)); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm("Delete this comparable evidence?")) return; await deleteComparable(propertyId, id); await refresh(); }
  function edit(item: PropertyComparable) { setTab(item.comparable_type); setEditing(item.comparable_id); setForm(Object.fromEntries(Object.entries({ ...emptyForm(item.comparable_type), ...item }).map(([key, value]) => [key, value == null ? "" : String(value)])) as FormState); }

  return <><MarketEstimateCard analysis={analysis} /><section className="command-card overview-section comparables-section">
    <div className="section-heading"><div><h2>Comparables</h2><p>Manually entered, dated evidence from permitted sources. No listing portals are scraped.</p></div><button className="workspace-action primary" onClick={() => void analyze()} disabled={busy}>{busy ? "Working…" : "Analyze Comparables"}</button></div>
    {error && <p className="media-error" role="alert">{error}</p>}
    <div className="comparable-tabs"><button className={tab === "sale" ? "active" : ""} onClick={() => setTab("sale")}>Sales</button><button className={tab === "rental" ? "active" : ""} onClick={() => setTab("rental")}>Rentals</button></div>
    <div className="comparable-form"><Field label="Source name" value={form.source_name} set={(v) => change("source_name", v)} /><Field label="Source URL" value={form.source_url} set={(v) => change("source_url", v)} /><Field label="Source record ID" value={form.source_record_id} set={(v) => change("source_record_id", v)} /><Field label="Address" value={form.address} set={(v) => change("address", v)} /><Field label="Distance miles" value={form.distance_miles} set={(v) => change("distance_miles", v)} /><Field label="Property type" value={form.property_type} set={(v) => change("property_type", v)} /><Field label="Subtype" value={form.property_subtype} set={(v) => change("property_subtype", v)} /><Field label="Units" value={form.unit_count} set={(v) => change("unit_count", v)} /><Field label="Bedrooms" value={form.bedrooms} set={(v) => change("bedrooms", v)} /><Field label="Bathrooms" value={form.bathrooms} set={(v) => change("bathrooms", v)} /><Field label="Square feet" value={form.square_feet} set={(v) => change("square_feet", v)} /><Field label="Lot acres" value={form.lot_acres} set={(v) => change("lot_acres", v)} /><Field label="Year built" value={form.year_built} set={(v) => change("year_built", v)} /><Field label="Condition" value={form.condition} set={(v) => change("condition", v)} />
      {tab === "sale" ? <><Field label="Sale price" value={form.sale_price} set={(v) => change("sale_price", v)} /><Field label="Sale date" type="date" value={form.sale_date} set={(v) => change("sale_date", v)} /></> : <><Field label="Total monthly rent" value={form.monthly_rent} set={(v) => change("monthly_rent", v)} /><Field label="Listing date" type="date" value={form.listing_date} set={(v) => change("listing_date", v)} /></>}
      <Field label="Status" value={form.status} set={(v) => change("status", v)} /><Field label="Notes" value={form.notes} set={(v) => change("notes", v)} />
    </div><div className="media-actions"><button onClick={() => void save()} disabled={busy}>{editing ? "Save Comparable" : `Add ${tab === "sale" ? "Sale" : "Rental"}`}</button>{editing && <button onClick={() => { setEditing(null); setForm(emptyForm(tab)); }}>Cancel</button>}</div>
    <label className="comparable-sort">Sort by <select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="match_score">Match score</option><option value="distance_miles">Distance</option><option value="date">Date</option><option value="value">Price/rent</option></select></label>
    <div className="repair-cost-table-wrap"><table className="repair-cost-table"><thead><tr><th>Comparable/source</th><th>Date / distance</th><th>Units / size</th><th>Price / rent</th><th>Match</th><th>Use</th><th>Actions</th></tr></thead><tbody>{shown.map((item) => <tr key={item.comparable_id}><td><strong>{item.address}</strong><br /><a href={item.source_url} target="_blank" rel="noreferrer">{item.source_name}</a></td><td>{item.sale_date || item.listing_date || "—"}<br />{item.distance_miles ?? "—"} mi</td><td>{item.unit_count ?? "—"} units · {item.square_feet?.toLocaleString() ?? "—"} sf</td><td>{money(item.sale_price ?? item.monthly_rent)}<br /><small>{item.comparable_type === "sale" ? `${money(item.price_per_unit)}/unit · ${money(item.price_per_square_foot)}/sf` : `${money(item.rent_per_unit)}/unit · ${money(item.rent_per_square_foot)}/sf`}</small></td><td>{item.match_score?.toFixed(0) ?? "Not analyzed"}</td><td className={item.included ? "included" : "excluded"}>{item.included ? "Included" : `Excluded: ${item.exclusion_reason}`}</td><td><button onClick={() => edit(item)}>Edit</button> <button onClick={() => void remove(item.comparable_id)}>Delete</button></td></tr>)}</tbody></table></div>
  </section></>;
  function change(key: string, value: string) { setForm({ ...form, [key]: value }); }
}

function MarketEstimateCard({ analysis }: { analysis: ComparableAnalysis | null }) { return <section className="command-card overview-section"><h2>Market &amp; Rent Estimate</h2>{!analysis ? <p>Add and analyze comparable evidence to create estimates.</p> : <><div className="property-snapshot"><Fact label="Current Market Value" value={`${money(analysis.current_market_value_low)}–${money(analysis.current_market_value_high)}`} /><Fact label="ARV" value={`${money(analysis.after_repair_value_low)}–${money(analysis.after_repair_value_high)}`} /><Fact label="Monthly Market Rent" value={`${money(analysis.estimated_monthly_market_rent_low)}–${money(analysis.estimated_monthly_market_rent_high)}`} /><Fact label="Annual Market Rent" value={money(analysis.estimated_annual_market_rent)} /><Fact label="Comparable Counts" value={`${analysis.sale_comparable_count} sales · ${analysis.rental_comparable_count} rentals`} /><Fact label="Average Distance" value={`${analysis.average_sale_distance ?? "—"} sale mi · ${analysis.average_rental_distance ?? "—"} rental mi`} /><Fact label="Confidence" value={`${Math.round(analysis.comparable_analysis_confidence * 100)}%`} /><Fact label="Status" value={analysis.comparable_analysis_status.replaceAll("_", " ")} /></div><p><strong>Limitations:</strong> {analysis.comparable_limitations.join(" · ")}</p><p><strong>Next:</strong> {analysis.recommended_comparable_action}</p><small>Comparable estimates remain separate from asking price, assessments, manual ARV/rent, and AI rehab estimates.</small></>}</section>; }
function Field({ label, value, set, type = "text" }: { label: string; value: string; set: (value: string) => void; type?: string }) { return <label>{label}<input type={type} value={value} onChange={(event) => set(event.target.value)} /></label>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-sm text-gray-500">{label}</p><p className="font-medium">{value}</p></div>; }
function number(value: string) { return value.trim() ? Number(value) : undefined; }
function payload(form: FormState): ComparableInput { return { comparable_type: form.comparable_type, source_name: form.source_name, source_url: form.source_url, source_record_id: form.source_record_id || undefined, address: form.address, distance_miles: number(form.distance_miles), property_type: form.property_type, property_subtype: form.property_subtype || undefined, unit_count: number(form.unit_count), bedrooms: number(form.bedrooms), bathrooms: number(form.bathrooms), square_feet: number(form.square_feet), lot_acres: number(form.lot_acres), year_built: number(form.year_built), condition: form.condition || undefined, sale_price: number(form.sale_price), sale_date: form.sale_date || undefined, monthly_rent: number(form.monthly_rent), listing_date: form.listing_date || undefined, status: form.status || undefined, notes: form.notes || undefined, included: true }; }
function sortValue(item: PropertyComparable, sort: string) { if (sort === "date") return Date.parse(item.sale_date || item.listing_date || "1970-01-01"); if (sort === "value") return item.sale_price || item.monthly_rent || 0; return item[sort as "match_score" | "distance_miles"] || 0; }
function message(error: unknown) { return error instanceof Error ? error.message : "Comparable operation failed."; }
