import {useCallback,useEffect,useState} from "react";
import {analyzeFinancingScenario,createFinancingScenario,getFinancingAnalysis,getFinancingHistory,listFinancingScenarios,updateFinancingScenario} from "../../services/financingService";
import type {FinancingAnalysis,FinancingScenario,FinancingScenarioInput,FinancingType} from "../../types/financing";
const money=(v?:number)=>v==null?"—":v.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const pct=(v?:number)=>v==null?"—":`${(v*100).toFixed(1)}%`; const ratio=(v?:number)=>v==null?"—":v.toFixed(2);
const blank:FinancingScenarioInput={scenario_name:"Conventional 25% down",financing_type:"conventional",down_payment_percentage:.25,interest_rate:.07,amortization_years:30,loan_term_months:360,interest_only_months:0,points_percentage:0,origination_fee:0,appraisal_fee:0,lender_fee:0,other_financing_costs:0,prepayment_penalty:0,closing_costs_financed:false,rehab_financed_amount:0,reserve_requirement:0,is_approved:false};
export default function FinancingSection({propertyId}:{propertyId:string}){
 const [scenarios,setScenarios]=useState<FinancingScenario[]>([]),[analysis,setAnalysis]=useState<FinancingAnalysis|null>(null),[history,setHistory]=useState<FinancingAnalysis[]>([]),[selected,setSelected]=useState(""),[form,setForm]=useState<FinancingScenarioInput>(blank),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const items=await listFinancingScenarios(propertyId);setScenarios(items);setSelected(current=>current||items[0]?.financing_scenario_id||"");setAnalysis(await getFinancingAnalysis(propertyId).catch(()=>null));setHistory(await getFinancingHistory(propertyId).catch(()=>[]));}catch(e){setError(e instanceof Error?e.message:"Could not load financing.");}finally{setLoading(false);}},[propertyId]); useEffect(()=>{void load();},[load]);
 function edit(item:FinancingScenario){setSelected(item.financing_scenario_id);const {financing_scenario_id:_id,property_id:_property,created_at:_created,updated_at:_updated,...values}=item;void _id;void _property;void _created;void _updated;setForm(values);}
 async function save(){setLoading(true);setError("");try{if(selected)await updateFinancingScenario(propertyId,selected,form);else{const item=await createFinancingScenario(propertyId,form);setSelected(item.financing_scenario_id);}await load();}catch(e){setError(e instanceof Error?e.message:"Scenario could not be saved.");}finally{setLoading(false);}}
 async function analyze(){if(!selected)return;setLoading(true);try{setAnalysis(await analyzeFinancingScenario(propertyId,selected));await load();}catch(e){setError(e instanceof Error?e.message:"Analysis failed.");}finally{setLoading(false);}}
 const set=(key:keyof FinancingScenarioInput,value:unknown)=>setForm({...form,[key]:value});
 return <section className="command-card financing"><div className="section-heading"><div><p className="eyebrow">Financing & debt service</p><h2>Leveraged underwriting scenarios</h2><p>Unlevered strategy results and saved offers remain unchanged. Screening only—not a lender quote.</p></div><button className="workspace-action primary" disabled={!selected||loading} onClick={()=>void analyze()}>Analyze scenario</button></div>{error&&<p className="media-error">{error}</p>}
 <div className="financing-layout"><div><h3>Saved scenarios</h3>{scenarios.map(item=><button key={item.financing_scenario_id} className={`scenario-button ${selected===item.financing_scenario_id?"active":""}`} onClick={()=>edit(item)}>{item.scenario_name}{item.is_approved?" · Approved":""}</button>)}<button className="scenario-button" onClick={()=>{setSelected("");setForm(blank);}}>+ New scenario</button></div><div className="comparable-form"><Text title="Scenario name" value={form.scenario_name} change={v=>set("scenario_name",v)}/><label>Financing type<select value={form.financing_type} onChange={e=>set("financing_type",e.target.value as FinancingType)}>{["cash","conventional","dscr","hard_money","private","seller_financing","custom"].map(x=><option key={x}>{x}</option>)}</select></label>{(["purchase_price","down_payment_amount","down_payment_percentage","loan_amount","interest_rate","amortization_years","loan_term_months","interest_only_months","points_percentage","origination_fee","appraisal_fee","lender_fee","other_financing_costs","balloon_payment_month","prepayment_penalty","rehab_financed_amount","reserve_requirement"] as const).map(key=><NumberField key={key} title={key.replaceAll("_"," ")} value={form[key] as number|undefined} change={v=>set(key,v)}/>)}<label><input type="checkbox" checked={form.closing_costs_financed} onChange={e=>set("closing_costs_financed",e.target.checked)}/> Finance closing costs</label><label><input type="checkbox" checked={form.is_approved} onChange={e=>set("is_approved",e.target.checked)}/> Approved scenario</label><Text title="Notes" value={form.notes||""} change={v=>set("notes",v)}/><button onClick={()=>void save()} disabled={loading}>Save scenario</button></div></div>
 {analysis&&<><h3>Latest leveraged results</h3><div className="offer-range"><Fact title="Monthly P&I" value={money(analysis.monthly_principal_interest)}/><Fact title="Annual debt service" value={money(analysis.annual_debt_service)}/><Fact title="Total cash required" value={money(analysis.total_cash_required)}/><Fact title="DSCR" value={ratio(analysis.debt_service_coverage_ratio)}/><Fact title="Leveraged monthly cash flow" value={money(analysis.leveraged_monthly_cash_flow)}/><Fact title="Cash-on-cash return" value={pct(analysis.cash_on_cash_return)}/><Fact title="LTV / LTC" value={`${pct(analysis.loan_to_value)} / ${pct(analysis.loan_to_cost)}`}/><Fact title="Break-even occupancy" value={pct(analysis.break_even_occupancy)}/><Fact title="Balloon balance" value={money(analysis.balloon_balance)}/></div><div className="property-snapshot"><Fact title="Purchase price / basis" value={`${money(analysis.input_snapshot.purchase_price as number)} · ${analysis.input_snapshot.purchase_price_basis||"—"}`}/><Fact title="Value / basis" value={`${money(analysis.input_snapshot.value as number)} · ${analysis.input_snapshot.value_basis||"—"}`}/><Fact title="Rehab / basis" value={`${money(analysis.input_snapshot.rehab_cost as number)} · ${analysis.input_snapshot.rehab_basis||"—"}`}/><Fact title="Rent / basis" value={`${money(analysis.input_snapshot.monthly_rent as number)} · ${analysis.input_snapshot.rent_basis||"—"}`}/></div><List title="Warnings" values={analysis.warnings}/><List title="Missing inputs" values={analysis.missing_inputs}/><List title="Limitations" values={analysis.limitations}/><h3>Stress tests</h3><div className="repair-cost-table-wrap"><table className="repair-cost-table"><thead><tr><th>Case</th><th>DSCR</th><th>Monthly cash flow</th><th>Cash-on-cash</th></tr></thead><tbody>{analysis.stress_tests.map(item=><tr key={item.case}><td>{item.case}</td><td>{ratio(item.debt_service_coverage_ratio)}</td><td>{money(item.leveraged_monthly_cash_flow)}</td><td>{pct(item.cash_on_cash_return)}</td></tr>)}</tbody></table></div></>}
 <h3>Analysis snapshot history</h3><div className="repair-cost-table-wrap"><table className="repair-cost-table"><thead><tr><th>Created</th><th>Scenario</th><th>Type</th><th>DSCR</th><th>Cash flow</th><th>CoC</th></tr></thead><tbody>{history.map(item=><tr key={item.financing_analysis_id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.scenario_name}</td><td>{item.financing_type}</td><td>{ratio(item.debt_service_coverage_ratio)}</td><td>{money(item.leveraged_monthly_cash_flow)}</td><td>{pct(item.cash_on_cash_return)}</td></tr>)}</tbody></table></div></section>;
}
function Fact({title,value}:{title:string;value:string}){return <div><span>{title}</span><strong>{value}</strong></div>} function List({title,values}:{title:string;values:string[]}){return values.length?<div><strong>{title}</strong><ul>{values.map(x=><li key={x}>{x}</li>)}</ul></div>:null} function Text({title,value,change}:{title:string;value:string;change:(v:string)=>void}){return <label>{title}<input value={value} onChange={e=>change(e.target.value)}/></label>} function NumberField({title,value,change}:{title:string;value?:number;change:(v:number|undefined)=>void}){return <label>{title}<input type="number" step="any" value={value??""} onChange={e=>change(e.target.value===""?undefined:Number(e.target.value))}/></label>}
