import { useCallback, useEffect, useState } from "react";
import { calculateOffer, getOfferAnalysis, getOfferHistory, recalculateOffer, saveManualOffer } from "../../services/offerAnalysisService";
import { getStrategyAnalysis } from "../../services/strategyAnalysisService";
import type { OfferAnalysis, OfferStrategy } from "../../types/offerAnalysis";

const money = (value?: number) => value == null ? "—" : value.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const percent = (value?: number) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export default function OfferCalculatorSection({ propertyId }: { propertyId: string }) {
  const [offer, setOffer] = useState<OfferAnalysis | null>(null); const [history, setHistory] = useState<OfferAnalysis[]>([]);
  const [strategy, setStrategy] = useState<OfferStrategy>("wholesale"); const [allowOverAsking, setAllowOverAsking] = useState(false);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [manual, setManual] = useState({ target: "", margin: "", notes: "" });
  const load = useCallback(async () => { setLoading(true); try { const saved = await getOfferAnalysis(propertyId).catch(() => null); setHistory(await getOfferHistory(propertyId).catch(() => [])); setOffer(saved); if (saved) { setStrategy(saved.selected_strategy); setAllowOverAsking(saved.allow_over_asking_offer ?? false); } else { setAllowOverAsking(false); const analysis = await getStrategyAnalysis(propertyId).catch(() => null); if (analysis?.recommended_strategy) setStrategy(analysis.recommended_strategy); } } finally { setLoading(false); } }, [propertyId]);
  useEffect(() => { void load(); }, [load]);
  async function run() { setLoading(true); setError(""); try { setOffer(offer ? await recalculateOffer(propertyId, strategy, allowOverAsking) : await calculateOffer(propertyId, strategy, allowOverAsking)); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Offer calculation failed."); } finally { setLoading(false); } }
  async function saveManual() { if (!manual.target) return; setLoading(true); try { await saveManualOffer(propertyId, Number(manual.target), manual.margin ? Number(manual.margin) : undefined, manual.notes || undefined); setManual({ target: "", margin: "", notes: "" }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Manual offer could not be saved."); } finally { setLoading(false); } }
  return <section className="command-card offer-calculator"><div className="section-heading"><div><p className="eyebrow">Offer Calculator</p><h2>Strategy-specific offer range</h2><p>Separate from the Opportunity Score. No contract or offer is sent.</p></div><button className="workspace-action primary" onClick={() => void run()} disabled={loading || strategy === "custom"}>{loading ? "Calculating…" : offer ? "Recalculate" : "Generate Offer"}</button></div>{error && <p className="media-error">{error}</p>}
    <label className="offer-strategy">Strategy<select value={strategy} onChange={event => setStrategy(event.target.value as OfferStrategy)}><option value="wholesale">Wholesale</option><option value="wholetail">Wholetail</option><option value="flip">Flip</option><option value="rental_hold">Rental Hold</option><option value="custom">Custom / Manual</option></select></label><label className="offer-over-asking"><input type="checkbox" checked={allowOverAsking} onChange={event => setAllowOverAsking(event.target.checked)} /> Allow over-asking offer</label>
    {offer && <><div className="offer-range"><Fact title="Seller asking price" value={money(offer.seller_asking_price)} /><Fact title="Economic MAO" value={money(offer.maximum_allowable_offer)} /><Fact title="Opening offer" value={money(offer.recommended_offer_low)} /><Fact title="Recommended offer" value={money(offer.recommended_offer)} /><Fact title="High offer" value={money(offer.recommended_offer_high)} /><Fact title="Discount to asking" value={percent(offer.estimated_discount_to_asking)} /><Fact title="Margin to MAO" value={percent(offer.margin_to_mao)} /><Fact title="Confidence" value={percent(offer.offer_confidence)} /></div><div className="property-snapshot"><Fact title="Selected strategy" value={label(offer.selected_strategy)} /><Fact title="Projected metric" value={`${offer.projected_metric_label ?? "—"}: ${offer.projected_metric_label?.includes("rate") ? percent(offer.projected_metric_low) : money(offer.projected_metric_low)}`} /><Fact title="Value basis" value={offer.value_basis ?? "—"} /><Fact title="Rehab basis" value={offer.rehab_basis ?? "—"} /><Fact title="Rent basis" value={offer.rent_basis ?? "—"} /><Fact title="Status" value={label(offer.offer_status)} /></div><List title="Strengths" values={offer.strengths ?? []} /><List title="Blockers" values={offer.blockers} /><List title="Warnings" values={offer.warnings} /><List title="Missing inputs" values={offer.missing_inputs} /><List title="Formula" values={offer.formula_notes} /><p><strong>Limitations:</strong> {offer.limitations.join(" · ")}</p></>}
    <div className="manual-offer"><h3>Save a separate manual offer</h3><div className="comparable-form"><Field title="Target offer" value={manual.target} set={value => setManual({ ...manual, target: value })} /><Field title="Target margin" value={manual.margin} set={value => setManual({ ...manual, margin: value })} /><Field title="Notes" value={manual.notes} set={value => setManual({ ...manual, notes: value })} /></div><button onClick={() => void saveManual()} disabled={loading || !manual.target}>Save Manual Offer</button></div>
    <h3>Saved offer history</h3><div className="repair-cost-table-wrap"><table className="repair-cost-table"><thead><tr><th>Created</th><th>Strategy</th><th>Status</th><th>Low / target / high</th><th>Economic MAO</th><th>Notes</th></tr></thead><tbody>{history.map(item => <tr key={item.offer_analysis_id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{label(item.selected_strategy)}</td><td>{label(item.offer_status)}</td><td>{money(item.recommended_offer_low)} / {money(item.recommended_offer)} / {money(item.recommended_offer_high)}</td><td>{money(item.maximum_allowable_offer)}</td><td>{item.manual_notes ?? item.formula_notes[0] ?? "—"}</td></tr>)}</tbody></table></div></section>;
}
function Fact({ title, value }: { title: string; value: string }) { return <div><span>{title}</span><strong>{value}</strong></div>; }
function List({ title, values }: { title: string; values: string[] }) { return values.length ? <div><strong>{title}:</strong><ul>{values.map(value => <li key={value}>{value}</li>)}</ul></div> : null; }
function Field({ title, value, set }: { title: string; value: string; set: (value: string) => void }) { return <label>{title}<input value={value} onChange={event => set(event.target.value)} /></label>; }
