import { useCallback, useEffect, useState } from "react";
import { deletePropertyMedia, listPropertyMedia, setPrimaryPropertyMedia, updatePropertyMedia, uploadPropertyMedia } from "../../services/propertyMediaService";
import type { PropertyMedia } from "../../types/propertyMedia";

export default function PropertyMediaGallery({ propertyId }: { propertyId: string }) {
  const [media, setMedia] = useState<PropertyMedia[]>([]); const [selected, setSelected] = useState<PropertyMedia | null>(null); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async () => { setLoading(true); try { const items = await listPropertyMedia(propertyId); setMedia(items); setSelected((current) => items.find((item) => item.media_id === current?.media_id) ?? items.find((item) => item.is_primary) ?? items[0] ?? null); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load photos."); } finally { setLoading(false); } }, [propertyId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const mutate = async (action: () => Promise<unknown>) => { try { await action(); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Photo update failed."); } };
  if (loading) return <section className="command-card overview-section"><h2>Property Photos</h2><p>Loading photos…</p></section>;
  return <section className="command-card overview-section media-gallery"><h2>Property Photos</h2><input aria-label="Upload property photo" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => { const file = event.target.files?.[0]; if (file) void mutate(() => uploadPropertyMedia(propertyId, file)); event.currentTarget.value = ""; }} />{error && <p className="media-error">{error}</p>}{selected ? <><button className="media-primary" onClick={() => setModal(true)}><img src={selected.public_url} alt={selected.caption || selected.original_filename} /></button><div className="media-actions"><button onClick={() => void mutate(() => setPrimaryPropertyMedia(propertyId, selected.media_id))}>Set primary</button><button onClick={() => { if (confirm("Delete this photo?")) void mutate(() => deletePropertyMedia(propertyId, selected.media_id)); }}>Delete</button></div><label>Caption<input value={selected.caption ?? ""} onChange={(event) => setSelected({ ...selected, caption: event.target.value })} onBlur={() => void mutate(() => updatePropertyMedia(propertyId, selected.media_id, { caption: selected.caption }))} /></label><label>Room category<input value={selected.room_category ?? ""} onChange={(event) => setSelected({ ...selected, room_category: event.target.value })} onBlur={() => void mutate(() => updatePropertyMedia(propertyId, selected.media_id, { room_category: selected.room_category }))} /></label><div className="media-thumbnails">{media.map((item) => <button key={item.media_id} className={item.media_id === selected.media_id ? "active" : ""} onClick={() => setSelected(item)}><img src={item.public_url} alt={item.caption || item.original_filename} /></button>)}</div>{modal && <div className="media-modal" role="dialog" aria-modal="true" onClick={() => setModal(false)}><img src={selected.public_url} alt={selected.caption || selected.original_filename} /></div>}</> : <p className="media-empty">No property photos yet. Upload an exterior, interior, or condition photo to begin.</p>}</section>;
}
